import { Header } from '@/components/header/Header'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.scss'

const poppins = Poppins({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	weight: ['300', '500', '400', '600', '700', '800', '900']
})

export const metadata: Metadata = {
	title: 'Ecobazar',
	description: 'Generated by create next app',
	icons: '/plant-logo.svg'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.className}`}>
				<Header />
				{children}
			</body>
		</html>
	)
}
